# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 19:21
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=255)),
                ('last_color_played', models.CharField(max_length=2)),
                ('player_keys', django.contrib.postgres.fields.jsonb.JSONField()),
                ('board', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
