# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 05:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('game_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.GameInstance')),
            ],
        ),
    ]
