# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('site', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('round_in_series', models.CharField(max_length=255)),
                ('player_white', models.CharField(max_length=255)),
                ('player_black', models.CharField(max_length=255)),
                ('result', models.CharField(max_length=255)),
                ('white_elo', models.CharField(max_length=255)),
                ('black_elo', models.CharField(max_length=255)),
                ('eco', models.CharField(max_length=255)),
                ('moves', models.TextField()),
            ],
        ),
    ]
