# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 02:13
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0002_auto_20170625_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialized_state', django.contrib.postgres.fields.jsonb.JSONField()),
                ('hash', models.CharField(max_length=255)),
                ('historical_games', models.ManyToManyField(to='computer.HistoricalGame')),
            ],
        ),
    ]
